<!DOCTYPE html>
<html>
<head>
    <title> Details Page </title>
</head>
<body>
    <h2>Second Page</h2>
        <form action="user" method="post">
        <!--This is a page-->
        <!-- This is what we want the user to see (view) -->
        <!-- input only-->
        
        <label for="name">homeAddress:</label>
        <input type="text" name="homeAddress" placeholder = "Enter your address" required><br>

       <!-- <label for="name">Title:</label>
        <input type="text" name="Title" placeholder = "Enter your Title" required><br>

        <label for="name">Enter Suburb:</label>
        <input type="text" name="homeAddress" placeholder = "Enter your address" required><br> -->

        <input type="submit" value="Submit"> <br>
        </form>
       
</body>
</html>