<!DOCTYPE html>
<html>
<head>
    
    <title> SIGNUP PAGE</title>
</head>
<body>
    <h2>Signup Page </h2>
    <form action=" User" method="post">
        <!--This is a page-->
        <!-- This is what we want the user to see (view) -->
        <!-- input only-->
        
        <label for="name">Name:</label>
        <input type="text" name="name" placeholder = "Enter your name" required><br>

        <label for="email">Email:</label>
        <input type="email" name="email" placeholder = "Enter your email" required><br>

        <label for="Identity Number">ID:</label>
        <input type="ID" name="ID" placeholder = "Your 13 digit Identity Number" required><br>

        <label for="password">password:</label> 
       <input type="password" name="password" placeholder = "Enter your passwowrd" required><br>



         <br>
       
       <input type="submit" value="Continue"> <br>
       


    </form>
</body>